Repository polyphony-chat/chorus, pull requests merged in 2023-05, with the labels that each got.

#55 Feature/guild creation deletion
  src/api/channels/messages.rs
  src/api/guilds/guilds.rs
  src/api/guilds/mod.rs
  src/api/mod.rs
  src/api/policies/instance/limits.rs
  src/api/schemas.rs
  src/api/types.rs
  src/errors.rs
  src/gateway.rs
  src/limit.rs
Labels: Status: Pending, Type: Enhancement

#72 Feature/feature locks
  Cargo.toml
  src/lib.rs
  src/types/entities/application.rs
  src/types/entities/attachment.rs
  src/types/entities/channel.rs
  src/types/entities/emoji.rs
  src/types/entities/guild.rs
  src/types/entities/integration.rs
  src/types/entities/message.rs
  src/types/entities/role.rs
  src/types/entities/security_key.rs
  src/types/entities/sticker.rs
  src/types/entities/team.rs
  src/types/entities/template.rs
  src/types/entities/user.rs
  src/types/entities/user_settings.rs
  src/types/entities/voice_state.rs
  src/types/entities/webhook.rs
  src/types/interfaces/guild_welcome_screen.rs
Labels: Status: Review Needed

#74 Add rest of gateway events (merge feature/full gateway coverage)
  Cargo.toml
  src/gateway.rs
  src/types/entities/application.rs
  src/types/entities/audit_log.rs
  src/types/entities/auto_moderation.rs
  src/types/entities/channel.rs
  src/types/entities/emoji.rs
  src/types/entities/guild.rs
  src/types/entities/guild_member.rs
  src/types/entities/message.rs
  src/types/entities/mod.rs
  src/types/entities/relationship.rs
  src/types/entities/role.rs
  src/types/entities/stage_instance.rs
  src/types/entities/sticker.rs
  src/types/entities/user.rs
  src/types/entities/voice_state.rs
  src/types/events/application.rs
  src/types/events/auto_moderation.rs
  src/types/events/call.rs
  src/types/events/channel.rs
  src/types/events/guild.rs
  src/types/events/identify.rs
  src/types/events/integration.rs
  src/types/events/interaction.rs
  src/types/events/invite.rs
  src/types/events/lazy_request.rs
  src/types/events/message.rs
  src/types/events/mod.rs
  src/types/events/passive_update.rs
  src/types/events/presence.rs
  src/types/events/ready.rs
  src/types/events/relationship.rs
  src/types/events/request_members.rs
  src/types/events/session.rs
  src/types/events/stage_instance.rs
  src/types/events/thread.rs
  src/types/events/user.rs
  src/types/events/voice.rs
  src/types/events/voice_status.rs
  src/types/events/webhooks.rs
  src/types/interfaces/interaction.rs
Labels: Status: Review Needed

#81 Feature/channel/delete
  src/api/auth/register.rs
  src/api/channels/channels.rs
  src/api/channels/messages.rs
  src/api/guilds/guilds.rs
  src/api/users/users.rs
  src/errors.rs
  src/types/entities/guild.rs
  tests/channel.rs
  tests/common/mod.rs
  tests/guild.rs
Labels: Status: Accepted, Type: Enhancement, Difficulty: Easy

#82 Feature: Modify channel
  src/api/channels/channels.rs
  src/types/schema/channel.rs
  tests/channel.rs
Labels: Status: Accepted, Type: Enhancement, Difficulty: Easy
