Repository polyphony-chat/chorus, pull requests merged in 2023-07, with the labels that each got.

#146 Bug/discord instance info unavailable
  src/instance.rs
  src/types/config/types/general_configuration.rs
Labels: Status: Review Needed

#144 Ratelimiter overhaul
  Cargo.toml
  src/api/auth/login.rs
  src/api/auth/register.rs
  src/api/channels/channels.rs
  src/api/channels/messages.rs
  src/api/channels/permissions.rs
  src/api/channels/reactions.rs
  src/api/common.rs
  src/api/guilds/guilds.rs
  src/api/guilds/member.rs
  src/api/guilds/roles.rs
  src/api/mod.rs
  src/api/policies/instance/instance.rs
  src/api/policies/instance/limits.rs
  src/api/policies/instance/mod.rs
  src/api/policies/instance/ratelimits.rs
  src/api/policies/mod.rs
  src/api/users/relationships.rs
  src/api/users/users.rs
  src/errors.rs
  src/gateway.rs
  src/instance.rs
  src/lib.rs
  src/limit.rs
  src/ratelimiter.rs
  src/types/config/types/general_configuration.rs
  src/types/config/types/subconfigs/limits/rates.rs
  src/types/entities/user.rs
  src/types/utils/rights.rs
  src/types/utils/snowflake.rs
  tests/common/mod.rs
  tests/relationships.rs
Labels: Status: Revision Needed

#147 Async Observer Trait
  Cargo.toml
  examples/gateway_observers.rs
  src/gateway.rs
Labels: Status: Review Needed

#152 Enable saving and loading LimitsConfiguration
  src/api/policies/instance/ratelimits.rs
  src/instance.rs
Labels: Type: Enhancement, Difficulty: Easy

#158 Bump crate versions
  Cargo.lock
  Cargo.toml
Labels: Type: Maintenance

#167 derive Updateable
  Cargo.lock
  Cargo.toml
  chorus-macros/Cargo.lock
  chorus-macros/Cargo.toml
  chorus-macros/src/lib.rs
  src/types/entities/channel.rs
Labels: Type: Maintenance

#168 Improve auto updating structs usage
  src/api/auth/login.rs
  src/api/auth/register.rs
  src/api/users/users.rs
  src/instance.rs
  tests/common/mod.rs
  tests/gateway.rs
  tests/invites.rs
Labels: Type: Enhancement
