Repository polyphony-chat/chorus, pull requests merged in 2023-06, with the labels that each got.

#87 Feature/reactions
  src/api/channels/reactions.rs
Labels: Status: Accepted, Difficulty: Easy

#94 Feature/permissions and roles
  examples/gateway_observers.rs
  src/api/auth/login.rs
  src/api/auth/register.rs
  src/api/channels/channels.rs
  src/api/channels/messages.rs
  src/api/channels/reactions.rs
  src/api/guilds/guilds.rs
  src/api/guilds/mod.rs
  src/api/guilds/roles.rs
  src/api/policies/instance/instance.rs
  src/api/users/users.rs
  src/errors.rs
  src/instance.rs
  src/limit.rs
  src/types/entities/guild.rs
  src/types/entities/role.rs
  src/types/events/message.rs
  src/types/schema/guild.rs
  tests/roles.rs
Labels: Status: Accepted

#95 Feature/permissions and roles
  src/api/guilds/roles.rs
  src/types/entities/role.rs
  src/types/schema/guild.rs
  src/types/schema/mod.rs
  src/types/schema/role.rs
  tests/roles.rs
Labels: Status: Accepted

#104 Boilerplate reduction
  images/polyphony-chorus-round-light.png
  images/polyphony-chorus-round.png
  images/polyphony-chorus.png
  images/polyphony-chorus8bit.png
  src/api/channels/channels.rs
  src/api/channels/messages.rs
  src/api/channels/permissions.rs
  src/api/channels/reactions.rs
  src/api/common.rs
  src/api/guilds/guilds.rs
  src/api/guilds/member.rs
  src/api/guilds/roles.rs
  src/api/mod.rs
  src/api/users/users.rs
  src/types/entities/attachment.rs
  src/types/entities/message.rs
Labels: Status: Accepted, Type: Enhancement, Type: Maintenance, Difficulty: Medium

#117 Simplify GatewayEvent
  examples/gateway_observers.rs
  src/gateway.rs
  src/types/events/resume.rs
  tests/message.rs
Labels: Status: Accepted

#114 Simplify Snowflake
  Cargo.toml
  src/types/config/mod.rs
  src/types/utils/mod.rs
  src/types/utils/snowflake.rs
Labels: Status: Review Needed

#126 Get channel messages
  src/api/channels/channels.rs
  src/types/schema/channel.rs
  tests/channel.rs
  tests/message.rs
Labels: Type: Enhancement

#128 Always use Snowflakes in args
  src/api/channels/channels.rs
  src/api/channels/reactions.rs
  src/api/guilds/guilds.rs
  src/api/guilds/member.rs
  src/api/guilds/roles.rs
  src/api/users/relationships.rs
  src/types/entities/guild_member.rs
  tests/channel.rs
  tests/common/mod.rs
  tests/guild.rs
  tests/member.rs
  tests/relationships.rs
  tests/roles.rs
Labels: Status: Revision Needed, Type: Enhancement

#134 Make ReactionMeta::get() return a Vec<PublicUser>
  src/api/channels/reactions.rs
  tests/common/mod.rs
Labels: Status: Accepted, Type: Bug, Type: Enhancement
