Repository polyphony-chat/chorus, pull requests merged in 2024-01, with the labels that each got.

#465 Minor instance updates
  src/instance.rs
Labels: Type: Maintenance, Difficulty: Easy

#472 Bump actions/setup-node in GHA workflow to v4
  .github/workflows/build_and_test.yml
Labels: Type: Maintenance

#474 Update h2 to 0.3.24 to fix vulnerability RUSTSEC-2024-0003
  Cargo.lock
Labels: dependencies

#475 Fix example in readme for #456
  README.md
Labels: Type: Maintenance

#473 Replace unmaintained actions-rs/toolchain by dtolnay/rust-toolchain
  .github/workflows/rust-clippy.yml
Labels: Type: Maintenance

#476 Update github/codeql-action to v3
  .github/workflows/rust-clippy.yml
Labels: Type: Maintenance
