Repository polyphony-chat/chorus, pull requests merged in 2024-06, with the labels that each got.

#501 Backend related updates
  Cargo.lock
  Cargo.toml
  src/types/config/types/guild_configuration.rs
  src/types/config/types/register_configuration.rs
  src/types/entities/guild.rs
  src/types/entities/guild_member.rs
  src/types/entities/mod.rs
  src/types/entities/user_settings.rs
  src/types/mod.rs
  src/types/schema/channel.rs
  src/types/utils/jwt.rs
  src/types/utils/mod.rs
  src/types/utils/rights.rs
  src/types/utils/serde.rs
Labels: Status: Review Needed, Type: Enhancement, dependencies

#502 Invites
  src/types/entities/channel.rs
  src/types/entities/invite.rs
  src/types/errors.rs
  src/types/schema/channel.rs
Labels: Status: Review Needed, Type: Enhancement

#503 Backend/invites
  src/types/entities/invite.rs
  src/types/schema/invites.rs
  src/types/schema/mod.rs
Labels: Status: Review Needed, Type: Enhancement

#505 Backend/messages
  Cargo.toml
  chorus-macros/Cargo.lock
  chorus-macros/src/lib.rs
  src/types/config/types/register_configuration.rs
  src/types/entities/application.rs
  src/types/entities/channel.rs
  src/types/entities/emoji.rs
  src/types/entities/guild.rs
  src/types/entities/guild_member.rs
  src/types/entities/invite.rs
  src/types/entities/message.rs
  src/types/entities/role.rs
  src/types/entities/user.rs
  src/types/events/voice_gateway/speaking.rs
  src/types/schema/channel.rs
  src/types/schema/guild.rs
  src/types/schema/message.rs
  src/types/utils/rights.rs
  src/types/utils/serde.rs
  src/types/utils/snowflake.rs
  tests/types.rs
Labels: Status: Review Needed, Type: Enhancement

#506 Bump chorus macros to 0.4.0
  Cargo.lock
  Cargo.toml
  chorus-macros/Cargo.lock
  chorus-macros/Cargo.toml
Labels: Type: Maintenance

#507 Update and add some types in support of the backend
  src/types/entities/channel.rs
  src/types/entities/role.rs
  src/types/entities/webhook.rs
  src/types/schema/channel.rs
  tests/channels.rs
Labels: Status: Review Needed, Type: Enhancement

#508 Implement gateway options, zlib-stream compression
  .github/workflows/build_and_test.yml
  Cargo.lock
  Cargo.toml
  examples/gateway_observers.rs
  examples/gateway_simple.rs
  src/api/users/users.rs
  src/gateway/backends/tungstenite.rs
  src/gateway/backends/wasm.rs
  src/gateway/gateway.rs
  src/gateway/message.rs
  src/gateway/mod.rs
  src/gateway/options.rs
  src/instance.rs
  src/types/entities/channel.rs
  src/types/entities/message.rs
  src/types/entities/user.rs
  src/types/events/presence.rs
  src/types/events/ready.rs
  src/types/schema/channel.rs
  src/types/schema/user.rs
  src/voice/gateway/backends/wasm.rs
  src/voice/gateway/gateway.rs
  tests/common/mod.rs
  tests/gateway.rs
Labels: Type: Enhancement

#509 Backend/guilds
  Cargo.lock
  Cargo.toml
  src/types/config/types/guild_configuration.rs
  src/types/entities/audit_log.rs
  src/types/entities/guild.rs
  src/types/entities/guild_member.rs
  src/types/entities/integration.rs
  src/types/entities/invite.rs
  src/types/entities/message.rs
  src/types/entities/role.rs
  src/types/entities/sticker.rs
  src/types/entities/voice_state.rs
  src/types/events/channel.rs
  src/types/events/guild.rs
  src/types/schema/audit_log.rs
  src/types/schema/guild.rs
  src/types/schema/invites.rs
  src/types/schema/message.rs
  src/types/schema/mod.rs
  src/types/schema/role.rs
  src/types/schema/voice_state.rs
  tests/common/mod.rs
  tests/gateway.rs
  tests/roles.rs
Labels: Status: Review Needed, Type: Enhancement

#512 Add custom deserializer for PermissionOverwriteType
  src/types/entities/channel.rs
Labels: Type: Enhancement

#514 Miscellaneous fixes
  Cargo.lock
  chorus-macros/Cargo.lock
  chorus-macros/Cargo.toml
  chorus-macros/src/lib.rs
  src/api/users/guilds.rs
  src/gateway/gateway.rs
  src/gateway/message.rs
  src/ratelimiter.rs
  src/types/entities/channel.rs
  src/types/entities/user.rs
  src/types/entities/user_settings.rs
  src/types/events/message.rs
  src/types/events/passive_update.rs
  src/types/events/presence.rs
  src/types/schema/guild.rs
Labels: Type: Bug, Type: Maintenance
