Repository polyphony-chat/chorus, pull requests merged in 2025-01, with the labels that each got.

#591 Add api for awaiting responses to gateway send events
  src/errors.rs
  src/gateway/events.rs
  src/gateway/gateway.rs
  src/gateway/handle.rs
  src/gateway/mod.rs
  src/gateway/observers.rs
  src/types/events/request_members.rs
  src/types/events/resume.rs
  tests/gateway.rs
Labels: Type: Enhancement, Type: New feature, Module: Gateway

#592 fix: #589
  src/api/invites/mod.rs
  src/api/users/guilds.rs
  src/types/schema/guild.rs
  src/types/schema/invites.rs
Labels: Type: Bug, Difficulty: Easy

#595 Feature/identify bitflags
  chorus-macros/src/lib.rs
  src/types/events/identify.rs
Labels: Type: Enhancement, Module: Gateway

#596 Add UserStatus variant "Unknown"
  src/types/entities/user_settings.rs
Labels: Type: Bug, Difficulty: Trivial

#597 Skip send_telemetry_headers when deserializing ClientProperties
  src/types/interfaces/client_properties.rs
Labels: Type: Bug

#598 Instance default events API
  src/gateway/events.rs
  src/instance.rs
  src/types/config/types/guild_configuration.rs
  src/types/events/passive_update.rs
Labels: Type: New feature, Module: Gateway
